language: node_js
node_js:
  - node
  - 8
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn run build
# auto deploy to github release page
deploy:
  provider: releases
  api_key:
    # check https://docs.travis-ci.com/user/deployment/releases/ for configurations
    secure: "xxxxxx"
  file: "./ext.zip"
  branches:
    only:
      - master
  on:
    tags: true
